### ISSUE TITLE
Fix tiles in TryAlgo in Paris

### ISSUE THREAD

**Issue by jilljenn** [jilljenn/tryalgo#68]
Stamen has gone https://github.com/python-visualization/folium/issues/1803
But we may find a workaround

**Comment by xtof-durr** [comment]
I used openstreetmap for some gps graph visualization in the past. Now this also does not work anymore. I guess because the number of api requests has exceeded some threshold. But may be this could be our solution. 
https://webia.lip6.fr/~durrc/Iut/optim/t/09-maxflow=3

Le 5 nov. 2023, 12:10, à 12:10, "Jill-Jênn Vie" ***@***.***> a écrit:

**Comment by jilljenn** [comment]
I found a workaround but I have yet to add it: https://github.com/python-visualization/folium/issues/1803#issuecomment-1793709591

**Comment by jilljenn** [comment]
Fixed! https://nbviewer.org/github/jilljenn/tryalgo/blob/master/examples/TryAlgo%20Maps%20in%20Paris.ipynb
